#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export EDITOR='vim'
export VISUAL='vim'
export CDPATH='.:~'

#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Directory listing

#alias ll='ls -alFh'
alias la='ls -A'
alias l='ls -CF'
alias latr='ls -lAtr'

# Easier navigation: .., ..., -
alias ..='cd ..'
alias ...='cd ../..'
alias -- -='cd -'
alias xxx='exit'

# File size
alias fs="stat -f '%z bytes'"
alias df="df -h"
alias du='du -ch'

# Package management
if [[ -x /usr/sbin/apt-get ]]; then
    alias update="sudo apt-get -qq update && sudo apt-get upgrade"
    alias install="sudo apt-get install"
    alias remove="sudo apt-get remove"
    alias search="apt-cache search"
elif [[ -x /usr/bin/yum ]]; then
    alias update="sudo yum update"
    alias install="sudo yum install"
    alias remove="sudo yum remove"
    alias search="sudo yum search"
fi

# MISC commands
alias gtfo="/dev/null"
alias stfu="/dev/null"
alias wtf="/dev/urandom"
alias mount='mount | column -t'
alias h='history'
alias psg="ps aux | grep -v grep | grep -i -e VSZ -e"
alias lvim='vim -c "normal '\''0"'
alias oops='sudo $(history -p \!\!)'
alias mux='tmuxinator'

# git aliases
alias gamend='git commit --amend --no-edit'
alias gg='git grep -in'
alias gs='git st'
alias ga='git add'
alias gb='git branch'

# setup worktunnel in .ssh/config
alias sshwt='ssh -A -t worktunnel ssh -A -t'
# setup hometunnel is .ssh/config
alias sshht='ssh -A -t hometunnel ssh -A -t'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
# apt-history
function apt-history(){
      case "$1" in
        install)
              cat /var/log/dpkg.log | grep 'install '
              ;;
        upgrade|remove)
              cat /var/log/dpkg.log | grep $1
              ;;
        rollback)
              cat /var/log/dpkg.log | grep upgrade | \
                  grep "$2" -A10000000 | \
                  grep "$3" -B10000000 | \
                  awk '{print $4"="$5}'
              ;;
        *)
              cat /var/log/dpkg.log
              ;;
      esac
}

# Create a new directory and enter it
function md() {
  mkdir -p "$@" && cd "$@"
}

if [[ -f "${ZDOTDIR}" ]]; then
    source "${ZDOTDIR}"/priv-aliases.sh
fi

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
