#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export EDITOR='vim'
export VISUAL='vim'
export CDPATH='.:~'

# Directory listing

alias ll='ls -AlFh'
alias la='ls -A'
alias l='ls -CF'
alias latr='ls -lAtr'
alias lla='ll -A'       
alias l1='ls -1A'       # All files in 1 column

# Easier navigation: .., ..., -
alias ..='cd ..'
alias ....='cd ../..'
alias xxx='exit'

# File size
alias fs="stat -f '%z bytes'"
alias df="df -h"
alias du='du -ch'

# Package management
if [[ -x /usr/sbin/apt-get ]]; then
    alias apt-update="sudo apt-get -qq update && sudo apt-get upgrade"
    alias apt-install="sudo apt-get install"
    alias apt-remove="sudo apt-get remove"
    alias apt-search="apt-cache search"
elif [[ -x /usr/bin/yum ]]; then
    alias rpg="rpm -qa | grep"
    alias yum="sudo yum"
    alias yum-update="sudo yum update"
    alias yum-install="sudo yum install"
    alias yum-remove="sudo yum remove"
    alias yum-search="sudo yum search"
fi

if (( $+commands[subscription-manager] )) ; then
    alias sm="sudo subscription-manager"
fi

# MISC commands
alias gtfo="/dev/null"
alias stfu="/dev/null"
alias wtf="/dev/urandom"
alias mount='mount | column -t'
alias h='history'
alias psg="ps aux | grep -v grep | grep -i -e VSZ -e"
alias lvim='vim -c "normal '\''0"'
alias mux='tmuxinator'
# alias sudo='sudo ' # need to figure out how to make this work
alias v='vim'

# docker
alias d='docker'
alias db='docker build'
alias dr='docker run'

# git aliases
alias gamend='git commit --amend --no-edit'
alias gg='git grep -in'
alias gs='git st'
alias ga='git add'
alias gb='git branch'

# setup worktunnel in .ssh/config
alias sshwt='ssh -A -t worktunnel ssh -A -t'
# setup hometunnel is .ssh/config
alias sshht='ssh -A -t hometunnel ssh -A -t'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
# apt-history
function apt-history(){
      case "$1" in
        install)
              cat /var/log/dpkg.log | grep 'install '
              ;;
        upgrade|remove)
              cat /var/log/dpkg.log | grep $1
              ;;
        rollback)
              cat /var/log/dpkg.log | grep upgrade | \
                  grep "$2" -A10000000 | \
                  grep "$3" -B10000000 | \
                  awk '{print $4"="$5}'
              ;;
        *)
              cat /var/log/dpkg.log
              ;;
      esac
}

# Create a new directory and enter it
function md() {
  mkdir -p "$@" && cd "$@"
}

# Set precmd for tmux
case "$TERM" in
    screen*)
        precmd () {
            print -Pn '\033k$(hostname)\033\\'
        }
    ;;
esac

# Backup funciton
bu() { cp "$1" "$1".backup-`date +%y%m%d`; }

if [[ -f "${ZDOTDIR}"/priv-aliases.sh ]]; then
    source "${ZDOTDIR}"/priv-aliases.sh
fi

export PATH="$HOME/.dotfiles/bin:$PATH"
command -v rbenv >/dev/null 2>&1 && eval "$(rbenv init -)"
